### ISSUE TITLE
Some error trying to run your first example

### ISSUE THREAD

**Issue by ericmelse** [matloff/dsld#1]
Hi, I try to run your first example:

`newData <- data.frame(age=c(36,43))
z <- dsldLinear(svcensus,'wageinc','gender',interactions=T,newData)
summary(z)`

As such the summary result replicates your example perfectly.
Next, I use your `$female` and `$female` but, instead of the expected result values, I get this error message:

`Error: unexpected '$' in "$"`

Maybe you can write me what I am doing wrong or any other alternative.

**Comment by matloff** [comment]
That expression $female is part of the output of the summary() call. It is not executable code. -- Norm

**Comment by ericmelse** [comment]
Yes, somehow I have missed running the command `summary(z)` and now that I have used it, indeed, I get the expected results.
Thank you for your help!
